# --- FOR DEVELOPMENT ---
FROM node:20-alpine

WORKDIR /app

# Copy package.json dan package-lock.json
COPY package.json .
COPY package-lock.json .

# Install dependensi
RUN npm install

# Expose port 3000
EXPOSE 3000

# Perintah default untuk menjalankan server development
CMD ["npm", "run", "dev"]